         apiVersion: apps/v1
         kind: Deployment
         metadata:
           name: nginx-deployment
           labels:
             app: nginx-exp
         spec:
           replicas: 3
           selector:
             matchLabels:
               app: nginx-exp
           template:
             metadata:
               labels:
                 app: nginx-exp
             spec:
               containers:
               - name: nginx
                 image: nginx:1.14.2
                 ports:
                 - containerPort: 80
